apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipat-control-api
spec:
  podSelector:
    matchLabels:
      app: ipat-control-api
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              ipat-role: smoke
      ports:
        - protocol: TCP
          port: {{ .Values.controlApi.port }}
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipat-usp-controller
spec:
  podSelector:
    matchLabels:
      app: ipat-usp-controller
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              ipat-role: smoke
      ports:
        - protocol: TCP
          port: {{ .Values.uspController.port }}
  egress: []
