apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipat-control-api
  labels:
    app.kubernetes.io/part-of: ipat
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipat-usp-controller
  labels:
    app.kubernetes.io/part-of: ipat
automountServiceAccountToken: false
